[package]
name = "modern-bnu-course-thesis"
version = "0.0.1"
entrypoint = "lib.typ"
authors = ["Euan"]
license = "MIT"
description = "北京师范大学课程论文模板。Modern Beijing Normal University Course Thesis."
repository = "https://github.com/EuanTop/modern-bnu-course-thesis"
keywords = ["Beijing Normal University", "thesis"]
categories = ["thesis"]
exclude = ["imgs"]

[template]
path = "template"
entrypoint = "thesis.typ"
thumbnail = "thumbnail.png"